### ISSUE TITLE
Script fails to execute

### ISSUE THREAD

**Issue by rajashekar1410** [DontShaveTheYak/cf2tf#82] opened 2022-10-14 01:47 UTC
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\git\__init__.py", line 89, in <module>
    refresh()
  File "C:\Program Files\Python310\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Program Files\Python310\lib\site-packages\git\cmd.py", line 389, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

**Comment by shadycuz** [comment] 2022-10-25 18:29
@rajashekar1410 sorry I missed this. This issue is a duplicate of #29. So I will close this one. That issue has some steps to help you fix this. Unfortunately, the temp file is created in a random directory, so you have to run a python command to find it. I will try to make the directory a known place so its easier to fix this. 

I will also look for a more permanent fix in the future. Thanks for opening the issue =)

**Closed by shadycuz** 2022-10-25 18:29 UTC
