### ISSUE TITLE
converting aws solution template fails with an exception: Did not find an item to parse in * replica.*.arn - ARN of the replica

### ISSUE THREAD

**Issue by vainkop** [DontShaveTheYak/cf2tf#113] opened 2023-03-01 10:29 UTC
Hi. I've tried to convert [aws-instance-scheduler.template](https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/aws-instance-scheduler.template) from [instance-scheduler-on-aws/templates](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/templates.html) & it fails with:
```
$ cf2tf aws-instance-scheduler.template 
// Converting aws-instance-scheduler.template to Terraform!
 existing repo found.
Traceback (most recent call last):
  File "/home/admin1/.pyenv/versions/3.9.13/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 94, in convert
    tf_resources = self.convert_to_tf(self.manifest)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 146, in convert_to_tf
    tf_resources.extend(converter(resources))
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 331, in convert_resources
    resolved_values = self.resolve_values(
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 181, in resolve_values
    data[key] = self.resolve_values(
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 181, in resolve_values
    data[key] = self.resolve_values(
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 197, in resolve_values
    resolved_list_values = [
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 198, in <listcomp>
    self.resolve_values(
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 181, in resolve_values
    data[key] = self.resolve_values(
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 197, in resolve_values
    resolved_list_values = [
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 198, in <listcomp>
    self.resolve_values(
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/convert.py", line 193, in resolve_values
    return allowed_func[key](self, value)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/conversion/expressions.py", line 408, in get_att
    valid_arguments, valid_attributes = doc_file.parse_attributes(docs_path)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/terraform/doc_file.py", line 17, in parse_attributes
    attributes = parse_section("Attributes Reference", file)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/terraform/doc_file.py", line 42, in parse_section
    items = parse_items(file)
  File "/home/admin1/.pyenv/versions/3.9.13/lib/python3.9/site-packages/cf2tf/terraform/doc_file.py", line 76, in parse_items
    raise Exception(f"Did not find an item to parse in {line}")
Exception: Did not find an item to parse in * `replica.*.arn` - ARN of the replica
```

**Comment by shadycuz** [comment] 2023-03-16 15:30
@vainkop Thanks for opening this issue. This is for sure a bug. 

What is happening is that there is a call to `Fn::GetAtt` and it's trying to find the `ARN` for some resource. To do these kinds of conversions we parse the Terraform source code documentation. This conversion is pretty straightforward. If Cloudformation has an Attribute called `ARN` then it's pretty likely that Terraform will have one called `arn`. But its not always this straightforward.  For S3 buckets it's `BucketName` on the Cloudformation side and `bucket` on the Terraform side. So while parsing the source code it has errored because of this line:
```
* `replica.*.arn` - ARN of the replica
```
Usually attributes in the Terraform documentation dont have `.` or `*`. So one or both of these is causing the issue.

I think there is another "bug" at play here though. Your Cloudformation template does not have any resources that would have a "replica". When we convert a Cloudformation resource type to a Terraform resource type we use a "search" to find the best match. Sometimes the search is wrong. I think it might be wrong in this case. 

So here are the three things that need fixed:
1. Fix `doc_file.py` to not choke on strange attribute names. Actually the `get_att` function should handle these errors better. Ideally, when we encounter errors converting a resource we should just comment out the failure and continue instead of crashing.
2. The error's need improved so it easier to see whats going on. I understood that it failed to parse "ARN" from the documentation but not on which Terraform resource or which line in the Cloudformation template.
3. If it did the wrong conversion from one resource type to another that will also need addressed. 

I will try and work on this when I get time.

**Comment by thoroc** [comment] 2023-04-14 07:59
Any update on that? I have found a similar error while trying to convert a dynamodb template. The outputs does have the `Arn` in cf.
```yaml
Description: The primary storage layer
Resources:
  mydynamodbtable:
    Type: AWS::DynamoDB::Table
...
Outputs:
  ExportsOutputFnGetAttmydynamodbtable:
    Value:
      Fn::GetAtt:
        - mydynamodbtable
        - Arn
    Export:
      Name: mydynamodbtable:ExportsOutputFnGetAttmydynamodbtable
```

**Comment by shadycuz** [comment] 2023-04-14 13:49
@thoroc Could you provide the stack trace for your error? Also, the last 20 or 30 lines of a debug run might be helpful.

**Comment by riez** [comment] 2023-04-25 04:19
@shadycuz this might help

```
debug: Converted type from AWS::DynamoDB::Table to aws_dynamodb_table
Traceback (most recent call last):
  File "/Users/riez/.pyenv/versions/3.11.0/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(tmpl_path.stem, cf_template, search_manger).convert()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/convert.py", line 92, in convert
    tf_resources = self.convert_to_tf(self.manifest)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/convert.py", line 139, in convert_to_tf
    tf_resources.extend(converter(resources))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/convert.py", line 297, in convert_resources
    valid_arguments, valid_attributes = doc_file.parse_attributes(docs_path)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 15, in parse_attributes
    attributes = parse_section("Attributes Reference", file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 37, in parse_section
    items = parse_items(file)
            ^^^^^^^^^^^^^^^^^
  File "/Users/riez/.pyenv/versions/3.11.0/lib/python3.11/site-packages/cf2tf/terraform/doc_file.py", line 69, in parse_items
    raise Exception(f"Did not find an item to parse in {line}")
Exception: Did not find an item to parse in * `replica.*.arn` - ARN of the replica
```

**Comment by shadycuz** [comment] 2023-06-18 13:41
@vainkop I took a closer look at this and I think the issue is with `AWS::ServiceCatalogAppRegistry::Application` resource. I do not see an equivalent in Terraform? 

I'm going to close this, but if you know the equivalent resource in terraform, please let me know and I will re-open.

**Closed by shadycuz** 2023-06-18 13:41 UTC
