### ISSUE TITLE
Tag conversion issue

### ISSUE THREAD

**Issue by robomnis** [DontShaveTheYak/cf2tf#62] opened 2022-08-28 15:12 UTC
Super minor, but for resource tags need some slight tweak to make them generate in the right format. 

Input (CloudFormation):
```
      Tags:
        - Key: Network
          Value: Public
        - Key: Name
          Value: Production VPC
```

Output:
```
  tags = [{'Key': '"Network"', 'Value': '"Public"'}, {'Key': '"Name"', 'Value': '"Production VPC"'}]
```

Should be:
```
tags = {
    Network = "Public"
    Name = "Production VPC"
    }
```

Current output errors for tags on `terraform plan`:
```
╷
│ Error: Invalid character
│ 
│   on vpc.tf line 104, in resource "aws_vpc" "vpc":
│  104:   tags = [{'Key': '"Network"', 'Value': '"Public"'}, {'Key': '"Name"', 'Value': '"Production VPC"'}]
│ 
│ Single quotes are not valid. Use double quotes (") to enclose strings.
╵
```

**Comment by shadycuz** [comment] 2022-09-06 03:47
Duplicate of #23 but I will keep this open because this will likely require a different solution.

**Comment by shadycuz** [comment] 2023-04-14 14:04
In version `0.4` we released an override feature https://github.com/DontShaveTheYak/cf2tf/pull/86. This feature is meant to add override behavior for specific resources but I think could be easily adapted to add an override behavior for every resource. That means it should now be pretty simple to reformat the tags property in a way that is compatible with Terraform.

**Closed** 2023-07-08 13:46 UTC
Labels: enhancement, good first issue, help wanted
