### ISSUE TITLE
TypeError: Found section SECTION but prop_value was list not dict.

### ISSUE THREAD

**Issue by jannyg** [DontShaveTheYak/cf2tf#19] opened 2022-06-20 10:56 UTC
Hi,

Thanks for the tool and I gave it a spin on a template that I had. Sadly it failed, but hopefully this can help to get the issue resolved. Let me know if you need any more information or testing.

macOS 12.4
Python 3.9.12
c2tf 0.2.0

````
// Converting cf.cfn to Terraform!
  [####--------------------------------]   13%  00:00:45 code has been checked out.
warning: No match found for Subscription, commenting out this argument.
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sns_topic.html.markdown
warning: redrive_policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue.html.markdown
Traceback (most recent call last):
  File "/usr/local/bin/cf2tf", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/app.py", line 44, in cli
    config = TemplateConverter(cf_template, search_manger).convert()
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 59, in convert
    tf_resources = self.convert_to_tf(self.manifest)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 111, in convert_to_tf
    tf_resources.extend(converter(resources))
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 289, in convert_resources
    arguments = props_to_args(resolved_values, valid_arguments, docs_path)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 426, in props_to_args
    tf_arg_name, tf_arg_value = convert_prop_to_arg(
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 460, in convert_prop_to_arg
    tf_arg, tf_values = parse_subsection(tf_arg_name, prop_value, docs_path)
  File "/usr/local/lib/python3.9/site-packages/cf2tf/convert.py", line 488, in parse_subsection
    raise TypeError(
TypeError: Found section ## FIFO queue but prop_value was list not dict.
````

**Comment by shadycuz** [comment] 2022-06-20 15:31
Thanks @jannyg, is this a template you can share with me? If you cant chare the whole template, can you share the resource that failed? It appears it failed while processing a sqs_queue. 

I think there is a couple of fixes here that could really improve things. 

1. If we do fail to process a resource, we shouldn't stop processing others. Ideally, we would display the resource in terraform but commented out.  
```HCL
// resource "some_bad_resource" "foo" {
// }
```
2. We should probably display more information as well
```console
warning: Failed to convert Cloudformation properties for $RESOURCE_NAME
```
Maybe even more in the debug output.
3. Overall better handling of Terraform subsections.

I think I see what the issue is, let me see if I can reproduce and get this fixed.

**Comment by jannyg** [comment] 2022-06-21 06:20
Thanks, here's the template. I just masked some account numbers from it, the rest should be unchanged.

[cloudformation.txt](https://github.com/DontShaveTheYak/cf2tf/files/8946299/cloudformation.txt)

**Comment by shadycuz** [comment] 2022-06-24 00:29
@jannyg Appears fixed in the most recent version. Just remember that it can only do about 75% of the conversion. It will need some manual clean up. 

```console
$ cf2tf --version
cf2tf, version 0.2.1
$ cf2tf cloudformation.txt 
// Converting cloudformation.txt to Terraform!
 existing repo found.
warning: No match found for Subscription, commenting out this argument.
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sns_topic_policy.html.markdown
warning: redrive_policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue.html.markdown
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue_policy.html.markdown
warning: redrive_policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue.html.markdown
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue_policy.html.markdown
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue_policy.html.markdown
warning: redrive_policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue.html.markdown
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue_policy.html.markdown
warning: policy does not have a section in /tmp/terraform_src/website/docs/r/sqs_queue_policy.html.markdown
warning: code_signing_config_arn does not have a section in /tmp/terraform_src/website/docs/r/lambda_function.html.markdown
warning: variables does not have a section in /tmp/terraform_src/website/docs/r/lambda_function.html.markdown
warning: assume_role_policy does not have a section in /tmp/terraform_src/website/docs/r/iam_role.html.markdown
```
It produced:
```hcl
variable "topic_name" {
  description = "Topic Name"
  type = string
  default = "splunk-s3-sqs-lambda"
}


resource "aws_sns_topic" "splunk_sns_topic" {
  name = var.topic_name
  // CF Property(Subscription) = [{'Protocol': '"sqs"', 'Endpoint': 'aws_sqs_queue.splunk_sqs.arn'}]
}


resource "aws_sns_topic_policy" "splunk_sns_policy" {
  policy = {
    Statement = [{'Sid': '"publish-from-s3"', 'Effect': '"Allow"', 'Principal': {'Service': ['"s3.amazonaws.com"']}, 'Action': '"sns:Publish"', 'Resource': 'aws_sns_topic.splunk_sns_topic.id', 'Condition': {'ArnLike': {'aws:SourceArn': '"arn:aws:s3:::111111111111-eu-north-1-logs"'}, 'StringEquals': {'aws:SourceAccount': '"1111111111111111"'}}}]
  }
}


resource "aws_sqs_queue" "splunk_sq_sdlq" {
  name = "1111111111111111-eu-north-1-logs-dlq"
}


resource "aws_sqs_queue" "splunk_sqs" {
  name = "1111111111111111-eu-north-1-logs"
  redrive_policy = {
    deadLetterTargetArn = aws_sqs_queue.splunk_sq_sdlq.arn
    maxReceiveCount = "500"
  }
}


resource "aws_sqs_queue_policy" "allow_sns2_sqs_policy" {
  queue_url = ['aws_sqs_queue.splunk_sqs.id']
  policy = {
    Version = "2012-10-17"
    Id = "PublicationPolicy"
    Statement = [{'Sid': '"Allow-SNS-SendMessage"', 'Effect': '"Allow"', 'Principal': {'Service': ['"sns.amazonaws.com"']}, 'Action': ['"sqs:GetQueueUrl"', '"sqs:GetQueueAttributes"', '"sqs:ListQueues"', '"sqs:SendMessage"'], 'Resource': 'aws_sqs_queue.splunk_sqs.arn', 'Condition': {'ArnLike': {'aws:SourceArn': 'aws_sns_topic.splunk_sns_topic.id'}, 'StringEquals': {'aws:SourceAccount': '"1111111111111111"'}}}]
  }
}


resource "aws_sqs_queue" "splunk_sq_scloudtraildlq" {
  name = "splunk-cloudtrail-sqs-dlq"
}


resource "aws_sqs_queue" "splunk_sq_scloudtrail" {
  name = "splunk-cloudtrail-sqs"
  redrive_policy = {
    deadLetterTargetArn = aws_sqs_queue.splunk_sq_scloudtraildlq.arn
    maxReceiveCount = "500"
  }
}


resource "aws_sqs_queue_policy" "allow_lambda2_sq_scloudtrail_policy" {
  queue_url = ['aws_sqs_queue.splunk_sq_scloudtrail.id']
  policy = {
    Version = "2012-10-17"
    Id = "PublicationPolicy"
    Statement = [{'Sid': '"Allow-Lambda-SQS-cloudtrail"', 'Effect': '"Allow"', 'Principal': {'AWS': '"*"'}, 'Action': ['"sqs:GetQueueUrl"', '"sqs:ReceiveMessage"', '"sqs:DeleteMessage"', '"sqs:GetQueueAttributes"', '"sqs:ListQueues"', '"sqs:SendMessage"'], 'Resource': ['aws_sqs_queue.splunk_sq_scloudtrail.arn'], 'Condition': {'ArnEquals': {'aws:SourceArn': 'aws_lambda_function.splunk_lambda_function.arn'}}}]
  }
}


resource "aws_sqs_queue_policy" "allow_lambda2_sq_scloudtraildlq_policy" {
  queue_url = ['aws_sqs_queue.splunk_sq_scloudtraildlq.id']
  policy = {
    Version = "2012-10-17"
    Id = "PublicationPolicy"
    Statement = [{'Sid': '"Allow-Lambda-SQS-cloudtraildlq"', 'Effect': '"Allow"', 'Principal': {'AWS': '"*"'}, 'Action': ['"sqs:GetQueueUrl"', '"sqs:ReceiveMessage"', '"sqs:DeleteMessage"', '"sqs:GetQueueAttributes"', '"sqs:ListQueues"', '"sqs:SendMessage"'], 'Resource': ['aws_sqs_queue.splunk_sq_scloudtraildlq.arn'], 'Condition': {'ArnEquals': {'aws:SourceArn': 'aws_lambda_function.splunk_lambda_function.arn'}}}]
  }
}


resource "aws_sqs_queue" "splunk_sq_svpcflowlogsdlq" {
  name = "splunk-vpcflowlogs-sqs-dlq"
}


resource "aws_sqs_queue" "splunk_sq_svpcflowlogs" {
  name = "splunk-vpcflowlogs-sqs"
  redrive_policy = {
    deadLetterTargetArn = aws_sqs_queue.splunk_sq_svpcflowlogsdlq.arn
    maxReceiveCount = "500"
  }
}


resource "aws_sqs_queue_policy" "allow_lambda2_sq_svpcflowlogs_policy" {
  queue_url = ['aws_sqs_queue.splunk_sq_svpcflowlogs.id']
  policy = {
    Version = "2012-10-17"
    Id = "PublicationPolicy"
    Statement = [{'Sid': '"Allow-Lambda-SQS-vpcflowlogs"', 'Effect': '"Allow"', 'Principal': {'AWS': '"*"'}, 'Action': ['"sqs:GetQueueUrl"', '"sqs:ReceiveMessage"', '"sqs:DeleteMessage"', '"sqs:GetQueueAttributes"', '"sqs:ListQueues"', '"sqs:SendMessage"'], 'Resource': ['aws_sqs_queue.splunk_sq_svpcflowlogs.arn'], 'Condition': {'ArnEquals': {'aws:SourceArn': 'aws_lambda_function.splunk_lambda_function.arn'}}}]
  }
}


resource "aws_sqs_queue_policy" "allow_lambda2_sq_svpcloflowsdlq_policy" {
  queue_url = ['aws_sqs_queue.splunk_sq_svpcflowlogsdlq.id']
  policy = {
    Version = "2012-10-17"
    Id = "PublicationPolicy"
    Statement = [{'Sid': '"Allow-Lambda-SQS-vpcflowlogsdlq"', 'Effect': '"Allow"', 'Principal': {'AWS': '"*"'}, 'Action': ['"sqs:GetQueueUrl"', '"sqs:ReceiveMessage"', '"sqs:DeleteMessage"', '"sqs:GetQueueAttributes"', '"sqs:ListQueues"', '"sqs:SendMessage"'], 'Resource': ['aws_sqs_queue.splunk_sq_svpcflowlogsdlq.arn'], 'Condition': {'ArnEquals': {'aws:SourceArn': 'aws_lambda_function.splunk_lambda_function.arn'}}}]
  }
}


resource "aws_lambda_function" "splunk_lambda_function" {
  code_signing_config_arn = {
    S3Bucket = "1111111111111111-eu-north-1-artifacts"
    S3Key = "lambda_splunk.zip"
  }
  description = "Lambda function for Splunk integration"
  function_name = "lambda-splunk"
  role = aws_iam_role.lambda_execution_role.arn
  runtime = "python3.8"
  handler = "lambda_function.lambda_handler"


  environment {
    variables = {
    CloudTrailQueueName = "splunk-cloudtrail-sqs"
    vpcflowlogsQueueName = "splunk-vpcflowlogs-sqs"
  }
  }
}


resource "aws_iam_role" "lambda_execution_role" {
  assume_role_policy = {
    Version = "2012-10-17"
    Statement = [{'Effect': '"Allow"', 'Principal': {'Service': ['"lambda.amazonaws.com"']}, 'Action': ['"sts:AssumeRole"']}]
  }
  force_detach_policies = [{'PolicyName': '"allowLambdaLogs"', 'PolicyDocument': {'Version': '"2012-10-17"', 'Statement': [{'Effect': '"Allow"', 'Action': ['"logs:*"'], 'Resource': '"arn:aws:logs:*:*:*"'}]}}, {'PolicyName': '"allowSqs"', 'PolicyDocument': {'Version': '"2012-10-17"', 'Statement': [{'Effect': '"Allow"', 'Action': ['"sqs:GetQueueUrl"', '"sqs:ReceiveMessage"', '"sqs:DeleteMessage"', '"sqs:GetQueueAttributes"', '"sqs:ListQueues"', '"sqs:SendMessage"', '"sqs:SendMessageBatch"'], 'Resource': ['aws_sqs_queue.splunk_sqs.arn', 'aws_sqs_queue.splunk_sq_scloudtrail.arn', 'aws_sqs_queue.splunk_sq_scloudtraildlq.arn', 'aws_sqs_queue.splunk_sq_svpcflowlogs.arn', 'aws_sqs_queue.splunk_sq_svpcflowlogsdlq.arn']}]}}]
}


resource "aws_lambda_event_source_mapping" "lambda_function_event_source_mapping" {
  batch_size = "10"
  enabled = "True"
  event_source_arn = aws_sqs_queue.splunk_sqs.arn
  function_name = aws_lambda_function.splunk_lambda_function.arn
}


output "my_topic_arn" {
  description = "Arn of Created SNS Topic"
  value = "Ref MySNSTopic"
}

```

**Closed** 2022-06-28 23:42 UTC
